### ISSUE TITLE
Sbt fails to load build

### ISSUE THREAD

**Issue by AugustNagro** [plokhotnyuk/jsoniter-scala#1037]
Hi, I just cloned jsoniter-scala, but am getting this error when running `sbt`:

```
jsoniter-scala $ sbt
[info] welcome to sbt 1.9.0 (Oracle Corporation Java 17.0.7)
[info] loading settings for project jsoniter-scala-build-build from sbt-updates.sbt ...
[info] loading project definition from /home/augustnagro/prog/jsoniter-scala/project/project
[info] loading settings for project jsoniter-scala-build from plugins.sbt ...
[info] loading project definition from /home/augustnagro/prog/jsoniter-scala/project
[info] loading settings for project jsoniter-scala from build.sbt,release.sbt,version.sbt ...
[info] resolving key references (12173 settings) ...
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
java.lang.RuntimeException: Nonzero exit value: 128
	at scala.sys.package$.error(package.scala:30)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:138)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:108)
	at $cd6b2c12261b88d30915$.oldVersion$lzycompute(build.sbt:6)
	at $cd6b2c12261b88d30915$.oldVersion(build.sbt:6)
	at $cd6b2c12261b88d30915$.isPatch$1(build.sbt:94)
	at $cd6b2c12261b88d30915$.$anonfun$publishSettings$2(build.sbt:98)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[error] Nonzero exit value: 128
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)

```

**Comment by plokhotnyuk** [comment]
@AugustNagro it fails on trying to get version from latest tag. Probably your local copy is too shallow. Please try cloning with depth that has at least one tag.

**Comment by AugustNagro** [comment]
Ok. It looks like forked repos don't include tags by default.

I'm now running `git fetch --tags upstream`, and it's downloading over 4GB? Do you know why it would be so high?

<img width="524" alt="Screen Shot 2023-06-20 at 2 01 22 PM" src="https://github.com/plokhotnyuk/jsoniter-scala/assets/6350134/f1a5a491-826f-4d9e-b998-90687d068492">
