### ISSUE TITLE
NPE during macro expansion

### ISSUE THREAD

**Issue by nilskp** [plokhotnyuk/jsoniter-scala#158]
I have a fairly nested hierarchy of case classes within objects within objects, which may be causing this problem. Not sure if this is helpful:
```
exception during macro expansion:   java.lang.NullPointerException 	at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:125) 	at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:102) 	at scala.reflect.internal.Reporter.echo(Reporting.scala:80) 	at scala.reflect.internal.Reporting$class.inform(Reporting.scala:63) 	at scala.reflect.internal.SymbolTable.inform(SymbolTable.scala:16) 	at scala.reflect.internal.Reporting$class.inform(Reporting.scala:47) 	at scala.reflect.internal.SymbolTable.inform(SymbolTable.scala:16) 	at scala.reflect.internal.SymbolTable.informProgress(SymbolTable.scala:59) 	at scala.reflect.internal.SymbolTable.informTime(SymbolTable.scala:60) 	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:213) 	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.load(SymbolLoaders.scala:227) 	at scala.reflect.internal.Symbols$Symbol.exists(Symbols.scala:1090) 	at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:163) 	at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:210) 	at scala.reflect.internal.Importers$StandardImporter$$anonfun$recreateType$4.apply(Importers.scala:248) 	at scala.reflect.internal.Importers$StandardImporter$$anonfun$recreateType$4.apply(Importers.scala:248) 	at scala.reflect.internal.Scopes$Scope.foreach(Scopes.scala:373) 	at scala.reflect.internal.Importers$StandardImporter.recreateType(Importers.scala:248) 	at scala.reflect.internal.Importers$StandardImporter.importType(Importers.scala:284) 	at scala.reflect.internal.Importers$StandardImporter$$anon$1.complete(Importers.scala:75) 	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1535) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$1.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:174) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127) 	at scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19) 	at scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$1.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:174) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.info(SynchronizedSymbols.scala:127) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$1.info(SynchronizedSymbols.scala:174) 	at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:167) 	at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:210) 	at scala.reflect.internal.Importers$StandardImporter.recreateType(Importers.scala:224) 	at scala.reflect.internal.Importers$StandardImporter.importType(Importers.scala:284) 	at scala.reflect.internal.Importers$StandardImporter.recreateType(Importers.scala:234) 	at scala.reflect.internal.Importers$StandardImporter.importType(Importers.scala:284) 	at scala.reflect.internal.Importers$StandardImporter$$anon$1.complete(Importers.scala:75) 	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1535) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$9.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:186) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127) 	at scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19) 	at scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$9.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:186) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.info(SynchronizedSymbols.scala:127) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$9.info(SynchronizedSymbols.scala:186) 	at scala.reflect.internal.Importers$StandardImporter$$anon$1.complete(Importers.scala:75) 	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1535) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$9.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:186) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127) 	at scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:15) 	at scala.tools.reflect.ReflectGlobal.gilSynchronized(ReflectGlobal.scala:13) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$9.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:186) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.info(SynchronizedSymbols.scala:127) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$9.info(SynchronizedSymbols.scala:186) 	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1680) 	at scala.reflect.internal.Definitions$DefinitionsClass.neverHasTypeParameters(Definitions.scala:909) 	at scala.tools.nsc.transform.SpecializeTypes.specializedTypeVars(SpecializeTypes.scala:434) 	at scala.tools.nsc.transform.SpecializeTypes.scala$tools$nsc$transform$SpecializeTypes$$specializeMember(SpecializeTypes.scala:928) 	at scala.tools.nsc.transform.SpecializeTypes$$anonfun$23$$anonfun$apply$21.apply(SpecializeTypes.scala:784) 	at scala.tools.nsc.transform.SpecializeTypes$$anonfun$23$$anonfun$apply$21.apply(SpecializeTypes.scala:783) 	at scala.collection.immutable.List.flatMap(List.scala:338) 	at scala.tools.nsc.transform.SpecializeTypes$$anonfun$23.apply(SpecializeTypes.scala:783) 	at scala.tools.nsc.transform.SpecializeTypes$$anonfun$23.apply(SpecializeTypes.scala:781) 	at scala.collection.immutable.List.flatMap(List.scala:338) 	at scala.tools.nsc.transform.SpecializeTypes.specializeClass(SpecializeTypes.scala:781) 	at scala.tools.nsc.transform.SpecializeTypes.transformInfo(SpecializeTypes.scala:1196) 	at scala.tools.nsc.transform.InfoTransform$Phase$$anon$1.transform(InfoTransform.scala:38) 	at scala.reflect.internal.Symbols$Symbol.rawInfo(Symbols.scala:1625) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$2.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$rawInfo(SynchronizedSymbols.scala:171) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$rawInfo$1.apply(SynchronizedSymbols.scala:128) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$rawInfo$1.apply(SynchronizedSymbols.scala:128) 	at scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:15) 	at scala.tools.reflect.ReflectGlobal.gilSynchronized(ReflectGlobal.scala:13) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$2.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:171) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.rawInfo(SynchronizedSymbols.scala:128) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$2.rawInfo(SynchronizedSymbols.scala:171) 	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1545) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$2.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:171) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127) 	at scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:15) 	at scala.tools.reflect.ReflectGlobal.gilSynchronized(ReflectGlobal.scala:13) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$2.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:171) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.info(SynchronizedSymbols.scala:127) 	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$2.info(SynchronizedSymbols.scala:171) 	at scala.reflect.internal.Symbols$Symbol.isDerivedValueClass(Symbols.scala:824) 	at scala.reflect.internal.transform.Erasure$ErasureMap.apply(Erasure.scala:131) 	at scala.reflect.internal.transform.Erasure$ErasureMap.eraseNormalClassRef(Erasure.scala:108) 	at scala.reflect.internal.transform.Erasure$ErasureMap.apply(Erasure.scala:132) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.preErase(Erasure.scala:1130) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1155) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:887) 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1345) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1166) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:887) 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1347) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1166) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:887) 	at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2559) 	at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2559) 	at scala.collection.immutable.List.loop$1(List.scala:176) 	at scala.collection.immutable.List.mapConserve(List.scala:200) 	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2559) 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1347) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1166) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:887) 	at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2559) 	at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2559) 	at scala.collection.immutable.List.loop$1(List.scala:176) 	at scala.collection.immutable.List.mapConserve(List.scala:200) 	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2559) 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1347) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1166) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1$$anonfun$transform$1.apply(Erasure.scala:1161) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1$$anonfun$transform$1.apply(Erasure.scala:1161) 	at scala.collection.immutable.List.map(List.scala:284) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1161) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:887) 	at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2559) 	at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2559) 	at scala.collection.immutable.List.loop$1(List.scala:176) 	at scala.collection.immutable.List.mapConserve(List.scala:200) 	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2559) 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1347) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1166) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:887) 	at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2559) 	at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2559) 	at scala.collection.immutable.List.loop$1(List.scala:176) 	at scala.collection.immutable.List.mapConserve(List.scala:200) 	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2559) 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1347) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1166) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:887) 	at scala.reflect.internal.Trees$$anonfun$itransform$1.apply(Trees.scala:1357) 	at scala.reflect.internal.Trees$$anonfun$itransform$1.apply(Trees.scala:1356) 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:17) 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1355) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1166) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:887) 	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2589) 	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2587) 	at scala.collection.immutable.List.loop$1(List.scala:176) 	at scala.collection.immutable.List.mapConserve(List.scala:200) 	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587) 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1366) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1166) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:887) 	at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1363) 	at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1361) 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:17) 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1360) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1163) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:887) 	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2589) 	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2587) 	at scala.collection.immutable.List.loop$1(List.scala:176) 	at scala.collection.immutable.List.mapConserve(List.scala:200) 	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587) 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1404) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:40) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:40) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:40) 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:40) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1166) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:887) 	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2563) 	at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1408) 	at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1407) 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:17) 	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1406) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16) 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555) 	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1166) 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:887) 	at scala.reflect.api.Trees$Transformer$$an	Json.scala
```

**Comment by nilskp** [comment]
Not sure where the LF went.

**Comment by nilskp** [comment]
Also not sure if access control plays a part. Some of the case classes are either `private` or private to the object.

**Comment by nilskp** [comment]
Changing the access control did seem to play a part, after removing it, I instead get this:
```
exception during macro expansion:   java.lang.ClassNotFoundException: <redacted>.Json$Foo$V1 	at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:62) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	at __wrapper$1$d8e5bbb09ac44ec888f5b938575d1ced.__wrapper$1$d8e5bbb09ac44ec888f5b938575d1ced$.wrapper(<no source file>:387) 	Json.scala
```
Note that I do remap leaf classes, like this:
```
adtLeafClassNameMapper = Map(
          classOf[Foo.V1].getName -> "FOO")
```
(there's more than one leaf class, but for brevity they're left out).

**Comment by plokhotnyuk** [comment]
@nilskp could you, please, prepare reproducible example based on [jsoniter-scala-examples](https://github.com/plokhotnyuk/jsoniter-scala/tree/master/jsoniter-scala-examples) project?

**Comment by nilskp** [comment]
@plokhotnyuk I'm under a deadline pressure right now, so it'll have to wait.

**Comment by plokhotnyuk** [comment]
Ok, as W/A just use string constants in the map function or rename classes to avoid name remapping...

**Comment by nilskp** [comment]
Seems the problem is that `Class.getName` returns `"Json.Foo$V1", but Jsoniter expects `"Json.Foo.V1"`.

**Comment by plokhotnyuk** [comment]
I think that source of the problem is that compiled cannot use `classOf` for classes in the same compilation module.
On other hand if model classes is already compiled then it works fine as in the following example:
```
    implicit val codec: JsonValueCodec[List[Either[String, String]]] =
      JsonCodecMaker.make[List[Either[String, String]]](CodecMakerConfig(adtLeafClassNameMapper = Map(
        classOf[Left[String, String]].getName -> "L",
        classOf[Right[String, String]].getName -> "R",
      )))

    println(readFromArray("""[{"type":"L","value":"left value string"}]""".getBytes("UTF-8")))
```

I will update documentation for `CodecMakerConfig` with warning about this case.
