### ISSUE TITLE
ClassNotFound exception at compile if define custom adtLeafClassNameMapper

### ISSUE THREAD

**Issue by twr143** [plokhotnyuk/jsoniter-scala#166]
```scala
object A {
...
def f(fullClassName: String) = {
    val shortName = fullClassName.substring(Math.max(fullClassName.lastIndexOf('.') + 1, 0))
    shortName.replaceAll("([A-Z])", "_$1").toLowerCase().substring(1)
  }
  implicit val codecIn: JsonValueCodec[Incoming] = JsonCodecMaker.make[Incoming](CodecMakerConfig(adtLeafClassNameMapper = f, discriminatorFieldName = "$type"))
...
}
```
causes
`exception during macro expansion: 
[error] java.lang.ClassNotFoundException: <package path>.A$
[error] 	at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:64)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)`

scala version is 2.12

However this one works ok:
```scala

  implicit val codecIn: JsonValueCodec[Incoming] = JsonCodecMaker.make[Incoming](CodecMakerConfig(adtLeafClassNameMapper =
    (fullClassName: String) => {
      val shortName = fullClassName.substring(Math.max(fullClassName.lastIndexOf('.') + 1, 0))
      shortName.replaceAll("([A-Z])", "_$1").toLowerCase().substring(1)
    }, discriminatorFieldName = "$type"))
```

**Comment by plokhotnyuk** [comment]
@twr143 you can pick up the latest version with more user friendly messages for that kind of compilation errors:

https://github.com/plokhotnyuk/jsoniter-scala/releases/tag/v0.34.1

**Comment by twr143** [comment]
Now message is this one
`
Cannot evaluate a parameter of the 'make' macro call for type 'motiv.evoTest.Model.Incoming'. It should not depend on code from the same compilation module where the 'make' macro is called. Use a separated submodule of the project to compile all such dependencies before their usage for generation of codecs.
`

**Comment by plokhotnyuk** [comment]
@twr143 it is better than just `java.lang.ClassNotFoundException` or `java.lang.StackOverflowException` ? WDYT, can it be improved more?
