### ISSUE TITLE
NPE when dealing with case classes containing non-Scala/Java data types

### ISSUE THREAD

**Issue by Tagar** [plokhotnyuk/jsoniter-scala#621]
NPE when dealing with case classes containing non-Scala/Java data types

```
Caused by: java.lang.NullPointerException
	at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeVal(JsonWriter.scala:263)
	at line2bf6e771f0214565bf00d2eff151d538147.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$KinesisSink$$anon$1.e0(command-3626532786886738:27)
	at line2bf6e771f0214565bf00d2eff151d538147.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$KinesisSink$$anon$1.encodeValue(command-3626532786886738:27)
	at line2bf6e771f0214565bf00d2eff151d538147.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$KinesisSink$$anon$1.encodeValue(command-3626532786886738:27)
	at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.write(JsonWriter.scala:525)
	at com.github.plokhotnyuk.jsoniter_scala.core.package$.writeToArray(package.scala:208)
	at line2bf6e771f0214565bf00d2eff151d538147.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$KinesisSink.process(command-3626532786886738:43)
	at line2bf6e771f0214565bf00d2eff151d538147.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$KinesisSink.process(command-3626532786886738:11)
	at org.apache.spark.sql.execution.streaming.sources.ForeachDataWriter.write(ForeachWriterTable.scala:140)
	at org.apache.spark.sql.execution.streaming.sources.ForeachDataWriter.write(ForeachWriterTable.scala:125)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$7(WriteToDataSourceV2Exec.scala:441)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1615)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:477)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:385)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:144)
	at org.apache.spark.scheduler.Task.run(Task.scala:117)

```

**Comment by plokhotnyuk** [comment]
@Tagar Hi, Ruslan! Thanks for your feedback! 
Could you please give a version number used for that? 
Do you have an ability to create a minimized example that reproduces the issue?
