### ISSUE TITLE
IndexOutOfBound

### ISSUE THREAD

**Issue by fggarcia** [plokhotnyuk/jsoniter-scala#889]
Hi, I upgrade from 2.12.4 to 2.13.13. Now I have this error trying to parse a body of struct:
STRUCT
```
case class BoosterContext(
    trainSize: Int,
    trainingTimeMillis: Long,
    rmse: BigDecimal,
    avgError: BigDecimal,
    percentiles: Map[String, BigDecimal]
)

case class JobTrainerResult(
    id: String,
    model: Option[Array[Byte]],
    context: Option[BoosterContext],
    source: Option[Array[Byte]],
    data: Option[Array[Byte]],
    test: Option[Array[Byte]],
    metadata: Option[String]
)
```

```
Error processing save java.lang.ArrayIndexOutOfBoundsException: Index 65533 out of bounds for length 65533 
>>>      at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:177) 
>>>        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:174) 
>>>     at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:62) 
>>>     at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
 >>>        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) 
 >>>     at java.base/java.lang.invoke.VarHandleByteArrayAsInts$ArrayHandle.index(VarHandleByteArrayAsInts.java:103) 
 >>>      at java.base/java.lang.invoke.VarHandleByteArrayAsInts$ArrayHandle.set(VarHandleByteArrayAsInts.java:130) 
 >>>   at com.github.plokhotnyuk.jsoniter_scala.core.ByteArrayAccess.setInt(ByteArrayAccess.java:24) 
 >>>    at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeByte(JsonWriter.scala:1160) 
 >>>   at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeVal(JsonWriter.scala:367) 
```

**Comment by plokhotnyuk** [comment]
@fggarcia Thanks for the reporting!

The bug was introduced in v2.13.12 by the following commit: https://github.com/plokhotnyuk/jsoniter-scala/commit/954c2832f8d9cc84a4198b427d2a2e56cf030c99

Please peek v2.13.14 that fixes it.

**Comment by fggarcia** [comment]
@plokhotnyuk thanks for quick fix!!! Tomorrow I will update the library. Thank you so much!!
