### ISSUE TITLE
getting an error passing Scala community build

### ISSUE THREAD

**Issue by imrafaelmerino** [plokhotnyuk/jsoniter-scala#933]
Hi! Im trying to add my library to de dotty community build and I'm getting this error

```code 
[error] java.lang.UnsupportedClassVersionError: com/github/plokhotnyuk/jsoniter_scala/core/ByteArrayAccess has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
4969
[error] 	at com.github.plokhotnyuk.jsoniter_scala.core.JsonReader.parseString(JsonReader.scala:2781)
4970
[error] 	at com.github.plokhotnyuk.jsoniter_scala.core.JsonReader.readKeyAsString(JsonReader.scala:90)
4971
[error] 	at json.value.spec.parser.JsObjSpecParser.parse(JsObjSpecParser.scala:32)
4972
[error] 	at json.value.spec.parser.JsObjSpecParser.parse(JsObjSpecParser.scala:24)
4973
[error] 	at json.value.spec.codec.JsObjCodec.decodeValue(JsObjCodec.scala:8)
4974
[error] 	at json.value.spec.codec.JsObjCodec.decodeValue(JsObjCodec.scala:7)
4975
[error] 	at com.github.plokhotnyuk.jsoniter_scala.core.JsonReader.read(JsonReader.scala:658)
4976
[error] 	at com.github.plokhotnyuk.jsoniter_scala.core.package$.readFromString(package.scala:162)
4977
[error] 	at json.value.spec.parser.JsValueParsersTests.testFun$proxy1$1(JsValueParserTests.scala:23)
4978
[error] 	at json.value.spec.parser.JsValueParsersTests.$init$$$anonfun$1(JsValueParserTests.scala:16)
```

I guess is because they are using Java 8 and that class was compile with a higher version of Java.

I'm using jsoniter-scala-core" % "2.13.38

According to the readme it seems I have to use 2.13.5 to work with Java 8 but not sure, that's why I'm asking.

Thanks in advance and have a nice day

**Comment by plokhotnyuk** [comment]
Yes, since 2.13.6 only Java 11+ are supported.
