### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index 100 out of bounds for length 100 during serialization of BigDecimal

### ISSUE THREAD

**Issue by Avatah** [plokhotnyuk/jsoniter-scala#998]
Hi

We noticed that some BigDecimal values cause exceptions during serialization.
Simple code that reproduces this problem:

```
import com.github.plokhotnyuk.jsoniter_scala.core.writeToString
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker

case class Test(value: BigDecimal)

object Test {
  def main(args: Array[String]): Unit = {
    implicit val codec = JsonCodecMaker.make[Test]
    val test           = Test(BigDecimal("0.0287500000000000000000"))
    val string         = writeToString(test)
  }
}
```

It throws:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 100 out of bounds for length 100
	at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.write8Digits(JsonWriter.scala:1574)
	at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.write18Digits(JsonWriter.scala:1586)
	at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeBigDecimalRemainder(JsonWriter.scala:1062)
	at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeBigDecimal(JsonWriter.scala:1055)
	at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeBigDecimal(JsonWriter.scala:1002)
	at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeVal(JsonWriter.scala:233)
	at motus.usage.allowance.common.Test$$anon$1.e0(Test.scala:10)
	at motus.usage.allowance.common.Test$$anon$1.encodeValue(Test.scala:10)
	at motus.usage.allowance.common.Test$$anon$1.encodeValue(Test.scala:10)
	at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeToString(JsonWriter.scala:533)
	at com.github.plokhotnyuk.jsoniter_scala.core.package$.writeToString(package.scala:545)
	at motus.usage.allowance.common.Test$.main(Test.scala:12)
	at motus.usage.allowance.common.Test.main(Test.scala)
```

**Comment by plokhotnyuk** [comment]
Hi, @ Avatah !

Thank you so much for reporting the issue!

Please pick the v2.20.2 release with a fix.
